module rf_types

  !
  ! Copyright (c) 2013 Australian National University
  !
  ! This program is is free software: you can redistribute it and/or
  ! modify it under the terms of the GNU General Public License as
  ! publised by the Free Software Foundation, either version 3 of the
  ! License, or (at your option) any later version.
  !
  ! Authors:
  !
  !   Rhys Hawkins 
  !   Thomas Bodin
  !   Malcolm Sambridge
  !
  ! For contact information, please visit:
  !   http://www.iearth.org.au/codes/RF
  !

  use, intrinsic :: iso_c_binding

  integer, parameter :: MAX_DATA_SIZE = 200
  integer, parameter :: MAX_PARTITIONS = 10

  type :: rfdata_t
     integer :: size
     real, dimension(MAX_DATA_SIZE) :: x, y, ymodel


     integer :: show_progress
     integer :: step
     integer :: total


	    integer nl_coll
	    integer nc_coll
	    integer nl_data
	    integer nc_data
	    integer nl_EL
		integer nc_EL

	    real*4 epsilo
		real*4 alpha,beta,gama
		real*4 alpha_r,beta_r,gama_r
		real*4 pi
		real*4 Hfinal
		real*4 Hdepth
		real*4 rho_coll,rho_rock
		real*4 preexp,preexp2
		real*4 Psi_Cl36_Ca_0,lambda_36,Lambda

		logical param_inv_sr_search ! search or not the slip-rate
        real*4 param_inv_srmin ! min slip-rate
        real*4 param_inv_srmax ! min max slip-rate
        real*4 param_inv_sr  ! slip-rate when fixed
        real*4 param_inv_sr_std !Std dev. of slip-rate value change
        real*4  param_inv_preexp ! long-term history duration
        logical param_inv_qs_search ! search or not the quiescence period
        real*4 param_inv_qs ! if quiescence period searched, max age of the top (yr)
        real*4 param_inv_qs_std ! if quiescence period searched, std of the max age of the top (yr)
        integer param_inv_nevmin ! min number of events
        integer param_inv_nevmax ! max number of events
        real*4 param_inv_agemin ! min age of events
        real*4 param_inv_agemax ! max age of events
! In the move process, a partition boundary is moved by a random amount
! sampled from a Gaussian variate with a zero mean and standard deviation
! of pd. Lowering this value will increase the Move acceptance rate, however
! setting this value too low may prolong convergence.
        real*4 param_inv_pd ! Std dev. of move changes (pd)
! When perturbing the value of event ages, the new value is obtained by
! adding a random Gaussian value with a mean of 0 and this standard
! deviation. Lowering this value will increase the acceptance rate
! of the Value process, however setting too low a value may prolong
! convergence.
        real*4 param_inv_age_std ! Std dev. of age value changes
! When creating a new partition (layer) the new value of Vs for the
! partition is obtained by adding to the previous value a random
! Gaussian value with a mean of 0 and this standard deviation. The
! death process (removing a layer) also uses this value. It is
! generally fine to leave this value the same as vs_std, but it
! may be adjusted lower to improve the birth and death acceptance
! rates.
        real*4 param_inv_age_stdbd ! Standart dev. of birth/death events
        integer param_inv_burnin ! Number of iterations to be thrown away
        integer param_inv_total  ! total number of iteration
! Seed and seed_mult control the initialisation of the random number
! generator. In the serial code, only the seed value is used. In the MPI
! code, the seed is generated by constructing a seed value from seed +
! mpi_rank * seed_mult.
        integer param_inv_seed   ! seed for random
        integer param_inv_seedmult   ! seed for random
        real*4 param_inv_ci ! credible interval

    real, dimension(:,:), allocatable :: data_rock
    real, dimension(1,62) :: data_coll
    real, dimension(:,:), allocatable :: data_sf

  real, dimension(:), allocatable :: EL_ti
  real, dimension(:), allocatable :: EL_it
  real, dimension(:), allocatable :: EL_f
  real, dimension(:), allocatable :: EL_mu

        real*4 Zs(5000)
        real*8 S_s(5000)
        real*4 so_f_beta_inf
        real*4 Lambda_f_beta_inf
        real*4 so_f_e
        real*4 Lambda_f_e
        real*4 Lambda_mu
        character (len=3) mu_model
        real*4 Param_site_lat
        real*4 Param_site_alt
!   LSD
        real*4 LSD_M(2383)
        real*4 LSD_t_M(2383)
        real*4 t_fineRc(76)
        real*4 lat_Rc(37)
        real*4 lon_Rc(25)
        real*4 t_Rc(45)
        real*4 MM0_KCL(76)
        real*4 lat_pp_KCL(76)
        real*4 lon_pp_KCL(76)
        real*4 S(120)
        real*4 SInf
        real*4 SPhiInf
        real*4 SPhi(120)
        real*4 O16nxBe10(200)
        real*4 O16pxBe10(200)
        real*4 SinxBe10(200)
        real*4 SipxBe10(200)
        real*4 O16nn2pC14(200)
        real*4 O16pxC14(200)
        real*4 SinxC14(200)
        real*4 SipxC14(200)
        real*4 Aln2nAl26(200)
        real*4 AlppnAl26(200)
        real*4 SinxAl26(200)
        real*4 SipxAl26(200)
        real*4 KnxCl36(200)
        real*4 KpxCl36(200)
        real*4 CanapCl36(200)
        real*4 CapxCl36(200)
        real*4 FenxCl36(200)
        real*4 FepxCl36(200)
        real*4 TinxCl36(200)
        real*4 TipxCl36(200)
        real*4 MgnxNe21(200)
        real*4 MgpxNe21(200)
        real*4 AlnxNe21(200)
        real*4 AlpxNe21(200)
        real*4 SinxNe21(200)
        real*4 SipxNe21(200)
        real*4 OnxHe3T(200)
        real*4 OpxHe3T(200)
        real*4 SinxHe3T(200)
        real*4 SipxHe3T(200)
        real*4 AlnxHe3T(200)
        real*4 AlpxHe3T(200)
        real*4 MgnxHe3T(200)
        real*4 MgpxHe3T(200)
        real*4 CanxHe3T(200)
        real*4 CapxHe3T(200)
        real*4 FenxHe3T(200)
        real*4 FepxHe3T(200)
        real*4 Natoms3
        real*4 Natoms10
        real*4 Natoms14
        real*4 Natoms26
        real*4 M_old(2383)
        real*4 Natoms36Ti
        real*4 Natoms36Fe
        real*4 Natoms36Ca
        real*4 Natoms36K
        real*4 dd(6)
        real*4 LSD_maxdepth
        real, dimension(:), allocatable :: depthvector
        real*4 Pressure
        real, dimension(:), allocatable :: flux_muon
        real*4 RcEst 
        real, dimension(:),allocatable :: flux_muon_R,flux_muon_phi
        real, dimension(:,:,:),allocatable :: muon36
        real, dimension(:,:,:),allocatable :: muon36_coll


  end type rfdata_t


end module rf_types
